### ISSUE TITLE
2nd Day of Month Templating Error

### ISSUE THREAD

**Issue by chitowncrispy** [SpectoLabs/hoverfly#1003]
## Description of the bug

When using a template such as `{{ now ‘0d’ ‘02’ }}` on the 2nd day of any month the wrong format is returned (`defaultDateTimeFormat = "2006-01-02T15:04:05Z07:00"`). Our project has a use case where we need only the current day to be returned in our json/xml mocks. As we have observed for a long time this fails whenever it is the second day of the month.

## Steps to reproduce the issue

Use the template `{{ now ‘0d’ ‘02’ }}` on the second day of the month.

### Observed result

`2022-02-02T15:04:05Z07:00`

**Hoverfly error messages seen (If none, say none)**
```
none
```
**If possible, add screenshots to help explain your problem**

### Expected result

`02`

## Additional relevant information
1. Hoverfly version: `1.3.3`
2. Suggested Fix

Currently this [line](https://github.com/SpectoLabs/hoverfly/blob/master/core/templating/template_helpers.go#L88) evaluates to `"02" == "02"` in this scenario. I would suggest changing this check on line 88 to the following:
```
if format == "02" && formatted == format {
   return formatted
} else if formatted == format {
   return now.UTC().Format(defaultDateTimeFormat)
}
```

**Comment by tommysitu** [comment]
that's a strange bug 😞 , probably not the way to validate golang datetime format with this: 
```
// when format is invalid
	if formatted == format {
		return now.UTC().Format(defaultDateTimeFormat)
	}
```

**Comment by tommysitu** [comment]
golang `Time.Format` doesn't validate the format, so assuming `formatted == format ` is a bit dangerous, and providing a fallback might be hiding the root cause even more. I've raise the PR to remove this check and just return whatever Golang decide the formatted string should be 🤷 . The templated date function would return the malformed format string if it's wrong which in my opinion easier to debug.
