### ISSUE TITLE
Validating Response from Real Service and returning Simulated data.

### ISSUE THREAD

**Issue by caarhern** [SpectoLabs/hoverfly#1070]
Hello Community, I don't know if someone is going to know this: I am trying to validate the response from the real service and if match certain criteria like response code been 500, I will return the response from the simulation data. How can I do this?

**Comment by kapishmalik** [comment]
@caarhern You can read through this doc supporting different modes https://docs.hoverfly.io/en/latest/pages/keyconcepts/modes/modes.html. @tommysitu any thoughts how to achieve this?

**Comment by tommysitu** [comment]
I don't think hoverfly supports it, the closest one is using modify mode, in which you can modify the response from the real service using middleware. You can take a look at the doc here: https://docs.hoverfly.io/en/latest/pages/keyconcepts/modes/modify.html

I'm going to close this one now since it's not really an issue
