### ISSUE TITLE
2way SSL is not supported

### ISSUE THREAD

**Issue by agnibrata** [SpectoLabs/hoverfly#190]
Hi Team,

I greatly like your product; which to our need. We appreciate your effort for making it open source. But we found that hoverfly doesn't support 2-way-ssl. 

B'coz of this we are not able to do virtualize any of our backend service in Cap1. Hope you will provide a fix for this which will enable us to use the tool smoothly.

**Comment by mogronalol** [comment]
Hello,

Thanks for this, we will add it to our roadmap and aim to implement it as soon as possible.

**Comment by agnibrata** [comment]
Thanks for the quick response, looking forward to your fix.

**Comment by tjcunliffe** [comment]
Hi @agnibrata - it would be great to get your input. We are doing some workshops with users over the next couple of weeks to help us develop the roadmap further. We hope to start building up the roadmap very soon - most likely using GitHub issues and milestones. Watch this space!

**Comment by mogronalol** [comment]
After some investigation, we are wondering if these solutions could work:

We can make Hoverfly configurable so you can set it to use the same certificate as the original client when communicating with the server.  Hoverfly would then needs a copy of the clients private key aswell, in order to decrypt the data and capture request / responses.  The problem with this would be storing the original clients private key within Hoverfly.  I can imagine this wouldn't be great for security reasons and I'm not sure how it would work if you want to proxy multiple clients with different certificates through Hoverfly.

The other alternative is to modify the server so it trusts Hoverfly's own client certificate, this would keep the clients private keys secret within the client, but then if the server is an external dependency then you might not be able to reconfigure certificates.

Do either of these options seem feasable, or did you have something else in mind?

**Comment by mogronalol** [comment]
I've opened an issue regarding this

https://github.com/SpectoLabs/hoverfly/issues/201

**Comment by benjih** [comment]
I'm closing this issue as we already have an enhancement ticket for two way SSL on #201
