### ISSUE TITLE
Failed to retrieve response from cache using BoltDB

### ISSUE THREAD

**Issue by benjih** [SpectoLabs/hoverfly#212]
When running Hoverfly as a webserver using a dataset persisted as a requests.db, I am unable to retrieve a response from the cache. The only way to get the data working is to export the data and then reimport it while Hoverfly is configured to be a webserver

**Comment by benjih** [comment]
The function that hashes the request for the key for the cache includes the host, which will not be the host of the webserver, meaning that the hashing function had to change. The issue occurs when data is stored in the cache when running as a proxy and uses the hash with the host.

The fix for this is rehash everything in the cache on startup.

**Comment by benjvi** [comment]
Agree with the suggestion @benjih only thing we will need to look out for is how much time this adds onto startup - we will need to test that as part of this issue

**Comment by rusenask** [comment]
thought you guys are the same person :D anyway, suggestion:

- read all captured payloads, this should happen instantly since you will probably never reach millions of captured requests.
- create a list of current hashes
- recreate hashes, this is also almost instant operation since current hashing techniques are very efficient which makes password hashing obsolete. 
- sort on keys & perform batch write (sorted inserts are much faster) https://github.com/boltdb/bolt#batch-read-write-transactions . This is also be very fast as long as you don't have more than 20,000 requests
- Delete previously saved list of hashes so only new remain

**Comment by benjih** [comment]
This has been resolved in the latest release of Hoverfly.
