### ISSUE TITLE
Is there any architecture document?

### ISSUE THREAD

**Issue by erkanerol** [SpectoLabs/hoverfly#338]
I am interested in Hoverfly and I want to know how it works, which components exist in it, how these components interact with others.

Is there any architecture document?

**Comment by benjih** [comment]
Hey @erkanerol,

There is currently no architecture documentation for Hoverfly. The reason for this is that we are currently in a beta stage and we often make changes to the architecture so that it is best suited to what is needed. Producing richer documentation including diagrams of the architecture will come as part of our 1.0 release.

The best way to follow the code is to look at core/hoverfly.go, specifically the processRequest(). This function is called to handle each request that is made to the proxy.
