### ISSUE TITLE
Hoverfly should record same request twice if headers are different

### ISSUE THREAD

**Issue by proofyman** [SpectoLabs/hoverfly#339]
Subj, right now we can  play mocks based on headers via templates, but we can't record mocks based on headers

**Comment by benjih** [comment]
Hey @proofyman,

Right now, when requests are captured, they are stored in a key value store based off of a hash of the request. When generating this hash, we ignore the headers. The reason why we do this is because depending on the HTTP client, the headers may be slightly different to the initial recording. This doesn't take into account having valid data you are using as part of your test in headers.

Maybe this issue and #329 could be combined to provide the option to either exclude recording headers or to record headers and include them in the hash.

**Comment by benjih** [comment]
Hey @proofyman,

Since this issue was opened, there has been a lot of changes to Hoverfly. One of the changes that happened in  [v0.11.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.0) was a change to `capture` mode in which additional parameters are needed to record headers. The other big change was moving to templates only. This means that matching will now always take headers into consideration.

I believe this issue is resolved, if not, please get back to me.
