### ISSUE TITLE
UI not reflecting traffic

### ISSUE THREAD

**Issue by johnharris85** [SpectoLabs/hoverfly#349]
`hoverctl start`
`hoverctl mode capture`

... run some requests ...

`hoverctl logs` (shows traffic)

UI doesn't show any traffic. Same behavior after logging in / logging out, restarting hoverfly, etc...

I don't see anything in developer tools, anywhere I should look to debug?

**Comment by JohnFDavenport** [comment]
The UI is currently minimal and it is on the roadmap to do something. This is the type of feedback we need to decide what to do.

But first, you should see some counters. Can you see them? I feel it is unlikely that is the problem, but please confirm.

More importantly, can you be a bit more explicit what you think is lacking? Are you looking for something that visually 'tails the logs' to help you debug your test? Perhaps an inverted list of the response/request pairs that reflects what is in the db at that point?

**Comment by shyal** [comment]
Hi John,

Could you try this:

```bash
hoverctl start
hoverctl mode capture
for i in range {0..10}; do
    curl -x http://localhost:8500 "http://time.jsontest.com"
done
hoverctl export simulation.json
hoverctl stop
```

And can you post your simulation.json here? Also what version of Hoverfly are you usin?

Thanks.

**Comment by johnharris85** [comment]
Version: 0.9.2

JSON attached. Seems to be capturing something? Only 1 pair though? In the UI it shows count 1 in the main graphic, but count 12 on the left-hand list?

[simulation.json.zip](https://github.com/SpectoLabs/hoverfly/files/696972/simulation.json.zip)

**Comment by johnharris85** [comment]
What do these messages mean? 

`[negroni] Completed 200 OK in 103.48µs
{"level":"info","message":"hi","msg":"Got message...","time":"2017-01-10T12:20:27-06:00"}`

**Comment by johnharris85** [comment]
OK so let's file this under 'not enough coffee' (https / https mismatch, issue with my REST client)

But I also get no results.db appearing, when does / should that happen?

**Comment by shyal** [comment]
Hi John,

Happens to the best of us. :)

> What do these messages mean?
> `[negroni] Completed 200 OK in 103.48µs {"level":"info","message":"hi","msg":"Got message...","time":"2017-01-10T12:20:27-06:00"}`

that's inside core/handlers/v1/stats_handler.go. It's the back and forth between the UI and the app; I think it's the WebSockets back & forth debugging messages.

> But I also get no results.db appearing, when does / should that happen?

We're in memory cache mode by default. I know that you can call hoverfly directly with the -db flag:

```
  -db string
    	Persistance storage to use - 'boltdb' or 'memory' which will not write anything to disk (default "boltdb")
```

I'm not sure what that flag is in hoverctl.

The default mode when launching hoverfly is boltdb, while the default mode when launching hoverctl is memory, which is confusing.

**Comment by benjih** [comment]
@shyal This is correct, it does need updating so that its in-memory by default regardless of execution method. There is no way of changing this through hoverctl currently but its on my TODO list.

@johnharris85 If you are making duplicate requests, Hoverfly will only store the request response pair once. Each request response pair is hashed on the request, so duplicate calls will overwrite each other.

The difference in numbers you are seeing maybe be due to measuring different things. That page will report the number of recordings and also the number of requests served in each mode. That counters table could probably have a clearer title.

**Comment by johnharris85** [comment]
Thanks!

> The default mode when launching hoverfly is boltdb, while the default mode when launching hoverctl is memory, which is confusing.

![47930163](http://s2.quickmeme.com/img/f0/f0b7609cb1bb382f12d43e048562dd94544005d1ec47af6990e08661f1c15c19.jpg)

I ask because I got a `results.db` once, but maybe I accidentally started hoverfly instead of hoverctl? *shrugs*

I'm assuming not, but is it possible to pass flags to `hoverctl start` and have them proxied through to `hoverfly`? Or is that beyond the scope of what `hoverctl` is trying to achieve?

**Comment by benjih** [comment]
Definitely within scope, I'll bump it up the list.

**Comment by shyal** [comment]
The issue here is that, unless I'm mistaken, changing the default storage mode on either `hoverctl` or `hoverfly` is a breaking changing. It's a breaking change, because if hoverfly, for example, was previously loading requests.db from disk by default, then when this fix gets released and it no longer does, tests may break.

I understand why the preferable storage mode is in memory, as it makes hover* more self-contained: the results only get affected by the dependencies, and data that get input explicitly into the application.

So a decision has to be made for how this will get fixed; continuing on this line of thinking means the best solution is to change hoverfly's default mode to in memory too, and as john suggested passing the flags from hoverctl to hoverfly.

If this is the most likely course of action, then it better be done quickly, as the more time goes on, and adoption-rate continues, the more difficult it will be to make breaking changes.

In this respect, I think sorting out this default mode for storage is a top priority.

**Comment by johnharris85** [comment]
My original questions were answered, so closing this
