### ISSUE TITLE
When is Upstream Proxy support being released?

### ISSUE THREAD

**Issue by jackreichelt** [SpectoLabs/hoverfly#402]
Basically the title. I read it in the docs and it looks to be exactly what I need to get Hoverfly working. Can't wait to get it going as it'll be extremely simple afterwards.

Cheers,
Jack

**Comment by benjih** [comment]
Hey @jackreichelt,

Its a bit confusing but the documentation refers to webserver mode as an upstream proxy because they theoretically do the same thing. As a result though, the features you are looking for may already exist.

Have a look at the [Running Hoverfly as a webserver](http://hoverfly.readthedocs.io/en/latest/pages/tutorials/asawebserver/asawebserver.html#webservertutorial) tutorial and see if this helps.

**Comment by benjih** [comment]
Ignore my previous comment, its early in the morning and I have been recovering from flu.

Hey @jackreichelt,

Upstream proxy will be being released today as v0.10.1. I will update this ticket when this release has been made.

**Comment by jackreichelt** [comment]
Hey there. Thanks for the update. I hope you feel better soon; the flu sucks.

**Comment by benjih** [comment]
Thanks for the well wishes @jackreichelt, its much appreciated.

(v0.10.1)[https://github.com/SpectoLabs/hoverfly/releases/tag/v0.10.1] of Hoverfly has just been released which includes upstream proxy.

I hope this helps you achieve what you are after.
