### ISSUE TITLE
cannot unmarshal object into Go value of type []v1.RequestResponsePairView

### ISSUE THREAD

**Issue by peel** [SpectoLabs/hoverfly#427]
I stumbled upon following issue:

1. Run hoverfly in  capture mode to create `simulation.json`
2. Run hoverfly in webserver mode to host the mocks: `hoverfly -webserver -import simulation.json`

results in:
```
[nix-shell:~/Downloads/wrk/castle_panel]$ hoverfly -webserver -import simulation.json
{"level":"info","msg":"Creating in memory map backend...","time":"2017-02-27T10:11:07+01:00"}
{"level":"warning","msg":"Turning off authentication...","time":"2017-02-27T10:11:07+01:00"}
{"error":"Got error while parsing payloads, error json: cannot unmarshal object into Go value of type []v1.RequestResponsePairView","import":"simulation.json","level":"fatal","msg":"Failed to import given resource","time":"2017-02-27T10:11:07+01:00"}
```

Whereas:
1. Run hoverctl start in  capture mode to create `simulation.json`
2. Run hoverfly via hoverctl in webserver mode to host the mocks: `hoverctl start webserver && hoverctl import simulation.json` 

exposes the mocks just fine

**Comment by benjih** [comment]
Hey @peel,

This is true. The reason for this is due to changing the JSON schema several versions ago and not changing the how the import flag works. The reason for this was due to encouraging people to use `hoverctl import` instead. 

The next version of Hoverfly drops support for the old JSON schema for simulations and as a result,  the flags have been updated to accept v2 simulations, solving your issue.

v0.11.0 is due within a week or so, I will update this ticket when it is out.

**Comment by benjih** [comment]
[v0.11.0](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.11.0) has now been released.
