### ISSUE TITLE
Passing parameters to middleware

### ISSUE THREAD

**Issue by mozey** [SpectoLabs/hoverfly#439]
I've tried using sys.argv 

`hoverctl middleware --binary python3 --script "middleware.py bar"`

and os.environ 

`hoverctl middleware --binary python3 --script "FOO=bar middleware.py"`

to pass parameters to python middleware without any luck. 

Is this possible?

**Comment by benjih** [comment]
Hey @mozey,

This is something that Hoverfly did before rewriting the middleware part of Hoverfly recently. When you are using that `--script` flag on hoverctl, you are sending the contents of that `middleware.py` file to Hoverfly to execute, rather than setting the command like previously.

As a work around, you could call the OS env in your middleware and then set the OS environment variable on the machine that Hoverfly is running on. This should mean that when Hoverfly executes the middleware, Python will check the environment variables instead of it being passed to the middleware process by Hoverfly.

I'm keen to know more as to why the environment variable is needed if you are happy to go into that?

**Comment by mozey** [comment]
> then set the OS environment variable on the machine that Hoverfly is running on

Thanks, that works.

> I'm keen to know more as to why the environment variable is needed if you are happy to go into that?

The reason I'm using middleware is I need to match wildcards in the POST body because of timestamps that change for every request. The middleware strips out the wildcards and hashes the request. I then read the response from path/to/HASH.json. For other developers the stubbed responses might be at a different path, I use the env to pass in this path.

The request templates only support wildcards in the path?
