### ISSUE TITLE
hoverctl login command returns "The handle is invalid" on Windows

### ISSUE THREAD

**Issue by tjcunliffe** [SpectoLabs/hoverfly#528]
On Windows 10

### Steps to reproduce:

1. Run `hoverctl login --new-target <target name> --host <host name>`

2. Enter a username when prompted

### Expected result:

User is prompted to enter a password

### Actual result:

`Password: The handle is invalid`

exit

config.yml contains:

```
default: default
targets: {}
```

**Comment by benjih** [comment]
Hey @tjcunliffe, 

This could be an issue regarding all user prompts on Windows. I will test this later today when I am near a Windows machine.

**Comment by benjih** [comment]
Having investigated this, this issue is describing two bugs.

The first bug is that the password prompt breaks on Windows. This is due to the file descriptor ID being used was hard coded. This is fine for non Windows systems, but not for Windows systems.

I have fixed this and there is a PR currently open for this.
https://github.com/SpectoLabs/hoverfly/pull/539

**Comment by benjih** [comment]
The second bug, which I will be investigating now is targets not be persisted in the config.yml file on Windows.

**Comment by benjih** [comment]
The bug appears to be an trying to use a POSIX style filepath on Windows systems. A PR has been raised to fix this.

This should be fixed for the next release, v0.11.4.
