### ISSUE TITLE
Cannot switch from current target host when starting new Hoverfly

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#542]
```
$ hoverctl targets default

+---------------------+-----+------------------------------------------------+------------+------------+
|     TARGET NAME     | PID |                      HOST                      | ADMIN PORT | PROXY PORT |
+---------------------+-----+------------------------------------------------+------------+------------+
| related-manufacture |   0 | foo.hoverfly.io |        443 |       8500 |
+---------------------+-----+------------------------------------------------+------------+------------+

$ hoverctl start 8081
Unable to start an instance of Hoverfly on a remote host (related-manufacture host: related-manufacture-mogronalol-dev.hoverfly.io)

Run `hoverctl start --new-target <name>`
$ hoverctl start --new-target default
Unable to start an instance of Hoverfly on a remote host (related-manufacture host: related-manufacture-mogronalol-dev.hoverfly.io)

$ hoverctl start --new-target default --host localhost
Unable to start an instance of Hoverfly on a remote host (related-manufacture host: related-manufacture-mogronalol-dev.hoverfly.io)
```

**Expected Behaviour:**

- When performing `Hoverctl start` it should default to localhost regardless of target (Remote starting isn't supported and is likely not going to be in this part of the CLI)

 performing Hoverctl

**Comment by tommysitu** [comment]
It's sensible to return a warning if the remote target doesn't support certain API calls. For single responsibility, calling `hoverctl start` without input flags should just try starting the default target, the same apply to all the other hoverctl commands. 

You can do target switching with the following flags:

`hoverctl start --new-target <target-name> `  
Creates and run a new local target (but not set it to default)

`hoverctl start --new-target <target-name> --set-default` 
Creates, run and set a new local target as default

`hoverctl start -t <existing-target-name>` 
Starts an existing target (obviously the target has to be local, otherwise you will get a warning message)
