### ISSUE TITLE
Ability to follow logs

### ISSUE THREAD

**Issue by mogronalol** [SpectoLabs/hoverfly#543]
When performing `hoverctl logs` it outputs all the logs but does not tail them. A follow argument would be useful, like ` -f or --follow`.

**Comment by benjih** [comment]
Hey @mogronalol,

hoverctl has always had `--follow-logs`, though currently it only returns JSON.

The next release will change `hoverctl logs` to return plain text logs. It introduces a new `--json` flag for those that want the logs in JSON format.

The `--follow-logs` flag will be renamed to `--follow`. This flag will work with either plain text or JSON logs. There is no shorthand flag for `--follow` yet due to the `-f` shorthand being used for `--force` elsewhere.

**Comment by mogronalol** [comment]
Could you treat the `-f`'s differently. So `logs -f` with the `-f` after is difference to `-f` elsewhere. That being said I'm not actually sure if that's a normal pattern / good practice - it could end up being confusing.

**Comment by benjih** [comment]
I'm not too sure either. I think its possible to have the two together shorthands to coexist based on what command they are being used with. The reason it hasn't been done so far as it would require reworking the `--force` flag and its shorthand as right now, its defined as a global flag, which it shouldn't be.
