### ISSUE TITLE
Update the Dockerfile so end users can specify startup mode

### ISSUE THREAD

**Issue by sherl0cks** [SpectoLabs/hoverfly#675]
Currently, you can only spin the container up in proxy mode with https://github.com/SpectoLabs/hoverfly/blob/master/Dockerfile#L11

**Comment by tommysitu** [comment]
@sherl0cks The Dockerfile we use to build Hoverfly docker image is this one actually: https://github.com/SpectoLabs/hoverfly/blob/master/core/Dockerfile
I have updated it to allow passing commands, so that you can start hoverfly in webserver mode using docker: 
`docker run -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:master -webserver`
Once this PR https://github.com/SpectoLabs/hoverfly/pull/676 is merged.

**Comment by sherl0cks** [comment]
ahh thanks for the redirect @tommysitu . looks like that PR is merged, closing this issue.

**Comment by psisodia** [comment]
Can anyone help me here, I have created hoverfly base image and added my git repo of API recordings to it. I can get image to build and run but I am unable to get hoverctl running. I need to use hoverctl in proxy mode for recording of APIs
