### ISSUE TITLE
HTTPS proxy returns incompatible headers with node.js client

### ISSUE THREAD

**Issue by nordicdyno** [SpectoLabs/hoverfly#727]
HTTPs proxy in capture and simulation mode returns both `Content-Length` and `Transfer-Encoding: chunked` headers. It' breaks node client (throws `HPE_UNEXPECTED_CONTENT_LENGTH` error).

OS: MacOS
Hoverfly version:  v0.16.0
node: v8.9.0

**Comment by JohnFDavenport** [comment]
Looks like Hoverfly shouldn't be setting the content length or your client should be ignoring it. We'll have a closer look.

**Comment by tommysitu** [comment]
#https://github.com/SpectoLabs/hoverfly/issues/697

**Comment by tommysitu** [comment]
It's related to this issue: https://github.com/SpectoLabs/hoverfly/issues/697

**Comment by tommysitu** [comment]
I think meeting the following requirements from [RFC7230](https://tools.ietf.org/html/rfc7230) should solve the `Content-Length` and `Transfer-Encoding` issues:
1. "A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field."
2. “In the absence of Transfer-Encoding, an origin server SHOULD send a Content-Length header field when the payload body size is known prior to sending the complete header section. “
3. "A server MUST NOT send a Transfer-Encoding/Content-Length header field in any
   response with a status code of 1xx (Informational) or 204 (No Content).
4. "A server MUST NOT send a Transfer-Encoding/Content-Length header field in
   any 2xx (Successful) response to a CONNECT request.”

The problem was that goproxy alwasy delete Content-Length header and set Transfer-Encoding header when handling HTTPS response for some reasons. 

Hoverfly on the other hand should have different behavior. In capture mode, it should just record the original headers faithfully. In simulation mode, I can think of two scenarios need special treatments: 
1. User does not provide Content-Length and Transfer-Encoding headers when the response has a body. This is quite common when the simulation is manually created, I think Hoverfly should add approriate header in this case. 
2. User modified the response body but not update the Content-Length header. This could happen when middlware was used to modify response body. Hoverfly should either work out the correct Content-Length or just set chucked transfer encoding.

**Comment by benjih** [comment]
Hey @nordicdyno 

This should now be fixed in [Hoverfly v0.17.1](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.17.1). If this is not the case and you still experience problems, please reopen this issue so that we can discuss further.
