### ISSUE TITLE
Cannot create a remote target

### ISSUE THREAD

**Issue by Yakimych** [SpectoLabs/hoverfly#770]
OS: Windows 10
hoverctl: master-2862
hoverfly: v0.17.1

I am trying to follow the instructions in [
Controlling a remote Hoverfly instance with hoverctl](https://hoverfly.readthedocs.io/en/latest/pages/tutorials/advanced/remotehoverfly/remotehoverfly.html) after pulling down and unzipping the hoverfly bundle on Windows into "C:\temp\hoverfly" that is present in my %PATH% variable (as per installation instructions).
Running `targets create` with verbose logging produces the following output:
```
> hoverctl targets create remote --host remote_ip --admin-port 8888 --proxy-port 8500 -v

time="2018-09-10T14:04:30+02:00" level=debug msg="Unsupported Config Type \"\""
Current target: local

time="2018-09-10T14:04:30+02:00" level=debug msg="Missing a config file"
time="2018-09-10T14:04:30+02:00" level=debug msg="Creating a new  a config file"

| TARGET NAME |     HOST     | ADMIN PORT | PROXY PORT | DEFAULT |
+-------------+--------------+------------+------------+---------+
| local       | localhost    |       8888 |       8500 | X       |
| remote      | remote_ip    |       8888 |       8500 |         |
+-------------+--------------+------------+------------+---------+
```

However, running `hoverctl targets` right after that produces the following output:
```
| TARGET NAME |     HOST     | ADMIN PORT | PROXY PORT | DEFAULT |
+-------------+--------------+------------+------------+---------+
| local       | localhost    |       8888 |       8500 | X       |
+-------------+--------------+------------+------------+---------+
```

Attempting to run commands against the remote produces the following:
```
> hoverctl -t remote mode capture
remote is not a target

Run `hoverctl targets create remote`
```

**Comment by benjih** [comment]
Hey @Yakimych,

Just tried this out and was able to recreate the issue. I will update again confirming whether or not this is a specific Windows issue or whether its OS independent. Currently, I think this issue is not OS specific. 

What is happening is [spf13/viper](https://github.com/spf13/viper) is erroring when the config is not found. Which is somewhat expected as it can't read config that is not there. I think how we may be handling this error may be wrong.

Good news is that this issue should only happen once and when it happens, a default config file should be written so it should not happen again unless you delete that config file.

If you see this error happen, repeat the previous command and hoverctl should work correctly the second time.

**Comment by benjih** [comment]
Just reran my test on Linux and did not experience this issue. I still think my explanation of the problem above is still relevant and I still believe the workaround of simply rerunning the command should bypass the issue on Windows.

I will look to see if I can add a better error message.

**Comment by tommysitu** [comment]
I can't reproduce the problem anymore with hoverfly `v0.17.7` on Windows 10, so I believe this issue has been fixed.
