### ISSUE TITLE
Unable to capture API for HSTS based websites.

### ISSUE THREAD

**Issue by pprraashant** [SpectoLabs/hoverfly#775]
I am unable to capture the API for HTTPS Strict Transport Security based website. 
I am using hoverfly as proxy server then trying to capture the API but when i set proxy. I will not able to access the website which uses HSTS. 

Can you please guide me how we can achieve this ...

**Comment by JohnFDavenport** [comment]
Hoverfly doesn't explicitly handle HSTS currently. Is anyone else hitting this problem?

**Comment by bnixon67** [comment]
I just started working with hoverfly and having the same issue. Using curl, I can use the --insecure flag, which seems to work:

curl --proxy http://localhost:8500 https://api.weather.gov/alerts/active?point=39.1016,-94.5812 --cacert cert.pem --insecure

But I am trying to simulate an API called from HTML/JavaScript/XMLHttpRequest running in Chrome.

I added the hoverfly cert as a trusted root certificate, which allows me to go to https://example.com, but not https://weather.gov

**Comment by tommysitu** [comment]
@bnixon67 I can capture/simulate the weather.gov API using curl or from the browser fine.

```
192:simulations tommysitu$ hoverctl mode capture
Hoverfly has been set to capture mode
192:simulations tommysitu$ curl --proxy http://localhost:8500 https://api.weather.gov/alerts/active?point=39.1016,-94.5812
{
    "type": "FeatureCollection",
    "features": [],
    "title": "current watches, warnings, and advisories for 39.1016 N, 94.5812 W",
    "updated": "2019-02-11T23:39:00+00:00"
}
```
I have attached the captured simulation that showing response with HSTS headers. 
[weather_gov.txt](https://github.com/SpectoLabs/hoverfly/files/2853477/weather_gov.txt)

There is nothing special about the HSTS headers, and they are captured just like all the other response headers in Hoverfly. I think your problem is to do with untrusted cert. Have you tried adding Hoverfly self-signed cert to your system trust store / keychain?

**Comment by tommysitu** [comment]
Closing now as we cannot find an issue with capturing HSTS based website.

**Comment by pprraashant** [comment]
ohh Is it ? i will try in few days got busy in appium stuff. will update if we are able handle the HSTS based sites
