### ISSUE TITLE
Hoverfly Spy mode and nginx proxy_pass do not work together

### ISSUE THREAD

**Issue by ttiurani** [SpectoLabs/hoverfly#944]
The repository:

https://github.com/ttiurani/hoverflybug

contains instructions on how to reproduce with a local docker the bug with nginx's default `proxy_pass` not working with Hoverfly spy mode, when doing a PUT/POST with a body and there being a "headers" request matcher in Hoverfly's simulation file. Nginx fails the request Hoverfly sends with 400, where without hoverfly as proxy – or without any "headers" request matchers –  things work.

Replicates with the latest Hoverfly.

**Comment by tommysitu** [comment]
It's a very weird edge case. It doesn't work in `spy` mode with a header matcher in the simulation for certain condition:  

✅  spy mode with header matcher; the request is matched: Got 200 with simulated response
❌  spy mode with header matcher; the request is not matched: Got 400 from upstream nginx
✅  spy mode without header matcher; the request is matched: Got 200 with simulated response
✅  spy mode without header matcher; the request is not matched: Got the response from real server

When it fails, I got something like this: 
```
< HTTP/1.1 400 Bad Request
< Server: nginx/1.17.4
< Date: Tue, 25 Aug 2020 21:56:20 GMT
< Content-Type: text/html
< Content-Length: 155
< Connection: keep-alive
< Cf-Ray: -
< Hoverfly: Was-Here
< Hoverfly: Forwarded
<
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

Is it similar to what you get as well @ttiurani ? 

I'm not sure what the cause is yet, but will try to debug

**Comment by ttiurani** [comment]
> Is it similar to what you get as well @ttiurani ?

Yes, exactly the issue. Furthermore, if the request doesn't have a body at all, the passthrough seems to also works even with headers matchers. It's unfortunate nginx doesn't tell what exactly is wrong with it, but I'm thinking, because it needs the body, `Content-Length` would go wrong here, and this would be somehow maybe related to https://github.com/SpectoLabs/hoverfly/issues/818 , could it @tommysitu ?

**Comment by ttiurani** [comment]
Noticed a very likely related bug in templating:

If I have a `"headers"` matcher in my simulation, e.g.:

```
          "headers": {
            "Authorization": [
              {
                "matcher": "glob",
                "value": "Bearer test-*"
              }
            ]
          }
 ```

then in the response body a `{{ Request.Header.Authorization }}` returns an empty string. But if I remove the request "headers" matcher, I get the correct value printed to the response. @tommysitu

**Comment by tommysitu** [comment]
Hey @ttiurani I spotted where the problem is, the Hoverfly matching logic converts the header names to lower case, which somehow upset Nginx. Cloning the headers before matching should fix it: https://github.com/SpectoLabs/hoverfly/pull/945

Also removing the bit that reconstructs request, we can just forward the original request if there is no matching.

**Comment by tommysitu** [comment]
I've created another issue to keep track of the related bug

**Comment by ttiurani** [comment]
Thanks for the fixes! However, I did unfortunately now bump into a new bug:

```
INFO[2020-08-31T16:12:45Z] Going to call real server
ERRO[2020-08-31T16:12:45Z] There was an error when forwarding the request to the intended destination  error="Post \"/login" unsupported protocol scheme \"\"" mode=spy request="&map[body:
...
method:POST path:/login query:map[so:[00D4E0000000mMM]] scheme:http]" response="&map[error:nil response]
```

and nothing actually gets sent to nginx. I did build this myself, so first I thought this was about me somehow building the linux/amd64 binary wrong, but then I tried to build the commit https://github.com/SpectoLabs/hoverfly/commit/9a0eee5f5dfd41e4597dc0725010048e94187794 and did manage to get the same 400 error from nginx just fine.

So did your "Also removing the bit that reconstructs request" part perhaps now lose the original scheme? @tommysitu

**Comment by tommysitu** [comment]
Oh no, what request did you make?

**Comment by ttiurani** [comment]
It's the original involved code I used to test this, the body of a POST is big in this one, it is `-plain-http-tunneling` and also Netty, but the request looks fine. It even has in that journal log entry end the `scheme:http`.

I didn't yet try without -plain-http-tunneling and curl.

**Comment by ttiurani** [comment]
I created a new issue about this to https://github.com/SpectoLabs/hoverfly/issues/948 @tommysitu
